import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type CP = {
  children: ReactNode;
  comments: ReactNode;
  members: ReactNode;
};
const RootLayout = ({ children, comments, members }: CP) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <h1>{children}</h1>
        <div className="flex gap-4">
          {comments}
          {members}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
